# Generated by Django 5.0.6 on 2025-03-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loanapplication_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='amount',
            field=models.DecimalField(decimal_places=1, error_messages={'invalid': 'El monto debe ser un número con un máximo de 7 dígitos y 1 decimal.'}, max_digits=8),
        ),
    ]
