# Generated by Django 5.0.6 on 2025-03-27 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_cuil_alter_loanapplication_dni_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='timestamp',
            new_name='created_date',
        ),
    ]
