# Generated by Django 5.0.6 on 2025-03-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loanapplication_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='amount',
            field=models.DecimalField(decimal_places=1, error_messages={'invalid': 'El monto debe ser un número con un máximo de 10 dígitos y 1 decimal.'}, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Por favor, ingrese un correo electrónico válido.'}, max_length=254),
        ),
    ]
